import React, { useState }from "react";
import { View, Text, StyleSheet, Switch } from "react-native";
import { FlatList } from "react-native-gesture-handler";
import { SafeAreaView } from "react-native-safe-area-context";
import { Alarm } from "../data/alarm";
import { isEnabled } from "react-native/Libraries/Performance/Systrace";

const AlarmScreen = () => {
    const alarms: Alarm[] = [
        { id: 1, time: "07:00 AM", isActive: true, testSubject: "Probability", workingDay: [1, 1, 1, 1, 1, 1, 1] },
        { id: 2, time: "08:30 AM", isActive: true, testSubject: "Graph Theory", workingDay: [1, 0, 1, 1, 0, 1, 1] },
    ];

    const daySet = (id: number, day:number): boolean => {
        const alarm = alarms.find((item) => item.id === id); //Erreur de
        if (alarm){
            if(alarm.workingDay[day-1]){
                return true;
            }
        }
        return false;
    };
    const [isActive, setOnActive] = useState(false);

    const toogleSwitch = (id: number) => {
        //A switcher les etats d'une alarme
    };

    return (
        <SafeAreaView style={styles.container}>
            <View>
                {/* Motivation Text */}
                <Text style={styles.motivationText}>Motivation sentence generated by an IA</Text>

                {/* Next Alarm */}
                <View>
                    <Text style={styles.motivationText}>Next alarm: ▶️</Text>
                </View>

                {/* Will ring in */}
                <View>
                    <Text style={styles.textStyle}>Will ring in + calculated time from the next alarm</Text>
                </View>

                {/* Alarms List */}
                <FlatList
                    data={alarms}
                    keyExtractor={(item) => item.id.toString()}
                    renderItem={({ item }) => (
                        <View style={styles.listItemContainer}>
                            {/* Days and time printer */}
                            <View style={styles.listItemStyle}>
                                <View style={styles.dayPrinter}>
                                    <Text style={ daySet(item.id, 7) ? styles.daySetText: styles.dayNotSetText}>S</Text>
                                    <Text style={ daySet(item.id, 1) ? styles.daySetText: styles.dayNotSetText}>M</Text>
                                    <Text style={ daySet(item.id, 2) ? styles.daySetText: styles.dayNotSetText}>T</Text>
                                    <Text style={ daySet(item.id, 3) ? styles.daySetText: styles.dayNotSetText}>W</Text>
                                    <Text style={ daySet(item.id, 4) ? styles.daySetText: styles.dayNotSetText}>T</Text>
                                    <Text style={ daySet(item.id, 5) ? styles.daySetText: styles.dayNotSetText}>F</Text>
                                    <Text style={ daySet(item.id, 6) ? styles.daySetText: styles.dayNotSetText}>S</Text>
                                </View>
                                <Text style={styles.textStyleTime}>
                                    {item.time}
                                </Text>
                                <Text style={styles.textStyle}>
                                    {"📝 Quiz subject: " + item.testSubject}
                                </Text>
                            </View>
                            {/* Switch and three vertical points */}
                            <View style={styles.switchContainer}>
                                <Switch
                                    trackColor={{false: "#767577", true:"#81b0ff"}}
                                    thumbColor={isActive ? "#f5dd4b" : "#f4f3f4"}
                                    ios_backgroundColor="#3e3e3e"
                                    onValueChange={toogleSwitch}
                                    value={isActive}
                                />
                            </View>
                        </View>
                        
                    )}
                />
            </View>
        </SafeAreaView>
    );
};

/* 
    [ ] -Switcher les etats d'une alarme
    [ ] -Modifier le conteneur d'une alarme
*/

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        backgroundColor: "#1F1B1B",
    },
    dayNotSetText: {
        color: "white",
        marginRight: 5,
    },
    dayPrinter : {
        flex: 1,
        flexDirection: "row",
    },
    daySetText: {
        color: "blue",
        marginRight: 5,
    },
    listItemContainer : {
        flex: 1,
        flexDirection: "column",
        backgroundColor: "#3D3636",
        padding: 10,
        marginVertical: 5,
        borderRadius: 5,
        width: '90%',
        alignSelf: "center",
    },

    listItemStyle: {
        flex: 1,
        flexDirection: "column",
        backgroundColor: "#3D3636",
        padding: 10,
        marginVertical: 5,
        borderRadius: 5,
        width: '90%',
        alignSelf: "center",
    },
    motivationText: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FFF",
    },
    switchContainer :{

    },
    textStyle: {
        color: "#FFF", 
    },
    textStyleTime: {
        color: "#FFF",
        fontSize: 25 
    },
});

export default AlarmScreen;